version: "3.8"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=doctorwho3210
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 5
  database:
    container_name: database
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: doctorwho3210
      POSTGRES_USER: postgres
      POSTGRES_DB: coupons-processor
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d coupons-processor"]
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 5
  api:
    container_name: api
    build: .
    ports:
      - "8000:8000"
    environment:
      FLASK_APP: main.py
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: sh -c "flask migrate execute && flask --app main run --host=0.0.0.0 --port=8000"
  celery:
    container_name: celery
    build: .
    environment:
      FLASK_APP: main.py
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: sh -c "celery -A tasks worker --loglevel=INFO"

volumes:
  rabbitmq_data:
  pgdata: {}